### PR TITLE
fix #251 (finally)

### LINKED ISSUE #251: Popper does not update its position to fit entirely in viewport/document if it is overflowing
### CodePen demo

https://codepen.io/FezVrasta/pen/QvQQgv

### Steps to reproduce the problem

1. Simply resize the browser window and you'll notice part of the Popper begins to overflow the document edge at the boundaries.

### What is the expected behavior?

That it is fully visible in the viewport with no overflow on a single update (i.e., it fits within the content of the document excluding itself).

### What went wrong?

It overflows.

### PR DESCRIPTION
**Pull request by atomiks**
#251 has been left open too long I think, and this is the solution that @kybishop suggested, and the one I use personally, but it should be placed in `update()` so it works for resizing too.

Yes, it accesses the DOM and will reduce performance, but I don't think there's another way.  Please test the performance difference before/after to see.

`Object.assign()` is being used, which I believe is already being ponyfilled in the lib.

### CODE REVIEW

**Comment by FezVrasta** [comment]
Thanks! I'm going to take a look at this soon. How's the end result? No weird visual glitches or jumps?

**Comment by atomiks** [comment]
Looks like Object.assign isn't being transformed, probably need to add that babel plugin...

Test it here: https://codepen.io/anon/pen/Yavaav?editors=1010

**Comment by FezVrasta** [comment]
I see that some tests are failing even on Chrome and Firefox, which do support Object.assign natively.

Anyway maybe we better get rid of it and use basic assignment?

**Comment by atomiks** [comment]
Updated it.

I also updated the CodePen so you can scroll and see how the updates work there as well. (seems to be fine). I'm going to test IE11 in a second.

**Comment by atomiks** [comment]
✖ should update the tooltip position when changing the title
        IE 10.0.0 (Windows 8 0.0.0)
        IE 11.0.0 (Windows 10 0.0.0)

Looks like this test is failing for some reason...

**Comment by atomiks** [comment]
Did you measure the perf impact of it yet?

You mentioned that 1.14.0 updates in 0.3ms instead of 1ms, what is it with this change?

**Comment by FezVrasta** [comment]
It still looks smooth
image

**Pull request merged**
