### PR TITLE
Fix typo in tooltip-examples page

### PR DESCRIPTION
**Pull request by lagartoflojo**
It's = it is
Its = possessive pronoun

### CODE REVIEW

**Comment by FezVrasta** [comment]
May you sign the CLA please?

**Comment by lagartoflojo** [comment]
@FezVrasta For some reason, I cannot. 
I open https://cla-assistant.io/FezVrasta/popper.js?pullRequest=380, then I click on "Sign in with GitHub to agree", I sign in with GH, and then I get redirected to https://cla-assistant.io.
No confirmation or anything, and the signature does not get registered.

**Comment by FezVrasta** [comment]
Try with  cla-assistant.io/FezVrasta/popper.js

**Comment by lagartoflojo** [comment]
@FezVrasta heh, I just found the bug https://github.com/cla-assistant/cla-assistant/issues/247 and used that link. 👍

**Pull request merged**
