### PR TITLE
Upgrade bundlesize to 0.12.0

### PR DESCRIPTION
**Pull request by siddharthkp**
Upgraded bundlesize to support dot in repo name

### CODE REVIEW

**Comment by siddharthkp** [comment]
Hey @FezVrasta I don't see the token present in this build: https://travis-ci.org/FezVrasta/popper.js/builds/256400217

**Comment by FezVrasta** [comment]
It is defined tho... What could it be?

**Comment by siddharthkp** [comment]
Not sure, do you mind giving me admin access for a tiny while, so that I can see what's going on?

**Comment by FezVrasta** [comment]
Is it enough to set you as admin on this repo or something on travis?

**Comment by siddharthkp** [comment]
I think travis picks up privileges from github, so that should work. Not super sure though.

**Comment by FezVrasta** [comment]
I added you as collaborator (it's the only option I have) but I doubt it will be enough 🤔

**Comment by siddharthkp** [comment]
Nope, it's not. I'll try to replicate this on my fork.

**Comment by siddharthkp** [comment]
Works on the fork  ¯\_(ツ)_/¯

https://travis-ci.org/siddharthkp/popper.js/builds/256404859#L413

Can you show me a screenshot of your settings just to be sure. Feel free to DM on twitter if you don't want to put it here.

**Comment by FezVrasta** [comment]
There's nothing special

image

**Comment by siddharthkp** [comment]
That's super weird.

I'll run it in debug mode

**Comment by siddharthkp** [comment]
Don't need this PR anymore

**Comment by FezVrasta** [comment]
on master everything works fine, but on the PRs builds the token isn't accessible for some reason

**Pull request closed without merging**
