### PR TITLE
fix: Regression introduced by #596

### PR DESCRIPTION
**Pull request by FezVrasta**
@atomiks does this PR still keeps the fix introduced in #596? If so I'd like to merge this because it seems to fix [react-popper/#122](https://github.com/souporserious/react-popper/issues/122) as well.

### CODE REVIEW

**Comment by atomiks** [comment]
Why is  the top code still there? I'll take a look.

```js
  const popperStyles = this.popper.style;
  popperStyles.top = '';
  popperStyles.left = '';
  popperStyles[] = '';
```

**Comment by FezVrasta** [comment]
Sorry I forgot to get rid of it.

**Comment by atomiks** [comment]
Unfortunately this brings the bug back. 😓

**Comment by FezVrasta** [comment]
There was a typo 😓 may you check again please?

**Comment by atomiks** [comment]
Yeah I fixed that... brings it back unfortunately

**Comment by FezVrasta** [comment]
Oh, that sucks... That's a problem.

**Comment by FezVrasta** [comment]
Same if you unset the styles before the `data.offsets.reference` assignment?

**Comment by atomiks** [comment]
Nope... 😞

**Comment by atomiks** [comment]
Test here: https://codepen.io/anon/pen/Yavaav?editors=0010

cmd+f "function update"

I've commented out the "restoration", if you uncomment it and resize the window, the issue comes back

**Comment by FezVrasta** [comment]
https://codepen.io/FezVrasta/pen/EEpBVa?editors=0010

How's this? It seems to work to me

**Comment by atomiks** [comment]
That's working. What did you do?

**Comment by FezVrasta** [comment]
Check the latest commit

**Comment by atomiks** [comment]
😱 it might be the perfect solution..

**Comment by FezVrasta** [comment]
> _it was not_

😂

Anyway, seriously, it seems to work both to fix the react-popper bug and _your_ bug.

**Pull request merged**
