### PR TITLE
Test IE9 support

### PR DESCRIPTION
**Pull request by onigoetz**
Following question in #327
I run make this pull request to execute tests on IE9.

It's not meant to be merged :)

### CODE REVIEW

**Comment by onigoetz** [comment]
okay, saucelabs doesn't work that way :)

**Comment by FezVrasta** [comment]
You should define a custom browser here:

https://github.com/FezVrasta/popper.js/blob/master/packages/test/karma.conf.js#L84-L89

**Comment by onigoetz** [comment]
Oh, okay, I never used saucelabs before, so I naively tried :)

Hmm, travis doesn't re-run after my change. how can I trigger it manually ?

**Comment by FezVrasta** [comment]
https://travis-ci.org/FezVrasta/popper.js/builds/248339781

**Comment by FezVrasta** [comment]
Looks like you should include a polyfill for `requestAnimationFrame` and` cancelAnimationFrame`.

I would make sense to test this on a local machine (you can download Internet Explorer 9 VMs for free from Microsoft).

**Comment by onigoetz** [comment]
Sure, I just wanted a quick look without downloading a IE9 VM. but I will do it and post my results in the initial discussion

**Pull request closed without merging**
