### PR TITLE
Fix 180

### LINKED ISSUE #180: I'm confused with the padding of flip and preventOverflow in the doc
`preventOverflow.padding` is actually what I want, but their description are the same.

image

### PR DESCRIPTION
**Pull request by FezVrasta**
ping @bojoyzhou and @nblackburn, please let me know if it's clear now.

Fixes #180

### CODE REVIEW

**Comment by bojoyzhou** [comment]
Perfect

**Comment by nblackburn** [comment]
Will give this a test now and report back in a few minutes, thanks for your hard work.

**Comment by nblackburn** [comment]
Doesn't fix it for me sadly but am glad one of the issues was resolved.

**Comment by FezVrasta** [comment]
It's just a change in the documentation, I pinged you because you upvoted the issue.

**Pull request merged**
