### PR TITLE
[meta] Added bundlesize check

### PR DESCRIPTION
**Pull request by FezVrasta**

### CODE REVIEW

**Comment by siddharthkp** [comment]
@FezVrasta You're missing out on the github status because you have not enabled `Build pull request updates` on travis.

**Comment by FezVrasta** [comment]
It is enabled:
image

**Comment by siddharthkp** [comment]
Huh!

I saw some errors in your build: https://travis-ci.org/FezVrasta/popper.js/builds/249131822#L596
And because of that, it does not show the comparison to master in the logs.

**Comment by FezVrasta** [comment]
Is it something I should fix on my end?

**Comment by siddharthkp** [comment]
I'm not yet sure what went wrong, Can you restart this build: https://travis-ci.org/FezVrasta/popper.js/builds/249134821

**Pull request merged**
