### PR TITLE
Fix #333

### LINKED ISSUE #333: CSS margin not being accounted when positioning arrow
### CodePen demo

https://codepen.io/aristidesfl/pen/dRdLXr

### Steps to reproduce the problem

1. Make a popper with an arrow
2. Add a CSS margin to the popper

### What is the expected behavior?

Arrow should be centered with ref

### What went wrong?

Arrow is not centered.

### PR DESCRIPTION
**Pull request by FezVrasta**
Again I had to add a `getStyleComputedProperty` to properly fix the problem.

I think we should find a way to cache the value during the beginning of each update lifecycle to reduce the DOM accesses..

### CODE REVIEW

**Comment by FezVrasta** [comment]
ping @aristidesfl, please may you let me know if this fixes your problem?

**Comment by aristidesfl** [comment]
I checked out this branch, built, uploaded popper.js umd and used it in the codepen example: https://codepen.io/aristidesfl/pen/qXbYNY

**Comment by FezVrasta** [comment]
It doesn't look like the right build, there's no instance of `popperMarginSide`, which is a new variable I added to the code to fix this bug.

**Comment by FezVrasta** [comment]
This is a version with the right build of popper.js
https://codepen.io/FezVrasta/pen/vJLjxb

**Comment by aristidesfl** [comment]
Seems to be working, thanks! I don't understand why the version I got after building your PR is not the right own. 

On an unrelated note, should popper follow reference when you scroll in this case? https://codepen.io/aristidesfl/pen/qXbYPy

**Comment by FezVrasta** [comment]
I think you hit #302

**Pull request merged**
