### PR TITLE
fix(popper): Fixed regression #401

### LINKED ISSUE #401: Popper position update does not position itself entirely in viewport
### CodePen demo

https://codepen.io/anon/pen/YxvXRe

### Steps to reproduce the problem

1.  Resize the browser window to make it smaller (with sufficient speed)

### What is the expected behavior?

The popper's position should update to the correct position (entirely inside the viewport) instantly

### What went wrong?

It 'lags' and part of the popper is left outside the viewport as the window is resized

### Any other comments?

This seems to be a regression which was fixed by this issue: https://github.com/FezVrasta/popper.js/issues/251

### PR DESCRIPTION
**Pull request by FezVrasta**
This should fix #401 and don't break #302.

Please @atomiks may you verify that both the tickets are properly fixed please?

### CODE REVIEW

**Comment by atomiks** [comment]
Yes it fixes the issue I made, but can't verify the other issue atm

**Comment by FezVrasta** [comment]
Going to merge, if problems arises people of #302 blame yourself, you had plenty of time to help me verify this PR.

Thank you again atomiks for your help! 🤗

**Comment by nheath99** [comment]
Hi this does indeed break #302

**Comment by FezVrasta** [comment]
Thank you for the heads up, I'll se what I can do.

**Pull request merged**
