### PR TITLE
 Refactor positionFixed code + move logic to utils + reinstate scroll test + wrap irrelevant ones + fix scrolling issues

### PR DESCRIPTION
**Pull request by MrFrankel**
I have cleaned the code, moved the positioning logic into the utils, which seems to be the desired structure throughout the lib.

Also fixed a bug with scrolling and reinstated some tests.

hope this ones better!

### CODE REVIEW

**Comment by MrFrankel** [comment]
seems like i.e is giving trouble again, though I ran the test locally through IE and they passed.
I get them back anyway

**Comment by MrFrankel** [comment]
@FezVrasta Any chance to get a review on this?

**Comment by FezVrasta** [comment]
Hey sorry for the delay.

It seems like people still experience scrolling lags even with this new feature (https://github.com/FezVrasta/popper.js/issues/264#issuecomment-347909107), may you take a look?

If it doesn't solve this problem I don't understand what's the point of this feature.

**Comment by MrFrankel** [comment]
I think this latests version fixes id,
heres a plunker demo, try is with positionFixed true & false and see the difference.
https://plnkr.co/edit/Ui8fhDhkdVgWAs4YSDha?p=preview

**Comment by FezVrasta** [comment]
How's that this example doesn't seem to work?
https://plnkr.co/edit/v65pmPtkwX3nkp6KvS5b?p=preview

**Comment by MrFrankel** [comment]
It does seem not to work on fixed positioned elements as references. 
It seems that there are no test cases for this case, so I was unaware of this. 
I will fix this use case, add a test and update the PR, other then this case have you seen any other issues with the PR? any issues with the code?

**Comment by FezVrasta** [comment]
I'm just concerned about the stability of the library, I'm sorry but if you can't provide a PR that introduces a fully working implementation I'll have to revert your changes and decline your PR.

I can't afford the time to maintain this additional feature, and I was clear when you decided to work on this.

Please, if you are able to add test cases to cover all the possible use cases of this library, do so. Otherwise please do let me know it so I'll proceed with the revert.

**Comment by MrFrankel** [comment]
Ok, my bad, it seems the version of popper.js in the plunker was not the latest.
Ive set it to the latest version which is in this PR and it works for this case and the one in #264.
https://plnkr.co/edit/mslhXmgDPVAmjfZaOEpw?p=preview

However it still seems that this library is lacking tests for 'fixed' references so ill add some for that anyway.

Regarding the stability of this PR, while I cannot guarantee it will work perfectly I have made sure it passes all the tests with the feature on/off and I have made sure that the feature will in no way interfere with cases where the feature is off, so no current users will be effected.
I am obviously more then happy to track any issues that will result from this feature in the future.

However I do understand your concerns, it is your library and ultimately your decision, whatever you decide I will be ok with it.

**Comment by FezVrasta** [comment]
Ok thank you, I'll wait for some additional test from your side and I'll merge this once you are ready.

**Comment by MrFrankel** [comment]
@FezVrasta Any chance to get this merged? i've added test and all suited are green

**Comment by FezVrasta** [comment]
Great, thanks!

**Comment by MrFrankel** [comment]
Id like to test the changes, could you update the 1.13.0-next version please?

**Comment by FezVrasta** [comment]
it should be released as 1.13.0-next.1 now (or popper.js@next)

**Pull request merged**
