### PR TITLE
Fix some typos and grammar.

### PR DESCRIPTION
**Pull request by maaz93**
Hi!

Thanks for making this awesome library. 🎉 I noticed that there were a few typos and grammatical errors in the Popper docs. Also, I noticed that the docs are generated from the JSDocs. For now, I've edited the `.md` file directly in order to get your feedback. Once you're OK with the changes, I'll change the source files.

Things I've done:

1. Corrected typos
1. Highlighted some strings as `code` as they're referring to actual code
1. Split some sentences into two to make them grammatically correct
1. Normalized the placement of `.`s in the docs
    1. No `.`s in the doc tables
    1.  `.`s at the end of API descriptions

### CODE REVIEW

**Comment by FezVrasta** [comment]
Thanks the corrections look good, please go ahead.

**Comment by FezVrasta** [comment]
Any news on this?

**Comment by maaz93** [comment]
I have a local commit ready. Just a few final checks. Will update in a day or two

**Comment by maaz93** [comment]
I didn't notice initially, but the generated docs have a weird `^M` character. Is it expected or there is something that I'm missing here?

Also FYI, I'm on Windows.

**Comment by FezVrasta** [comment]
Umh nope that's not expected, maybe it's some Windows quirk. May you get rid of the compiled markdown so that I can generate it once this PR is merged please?

**Comment by maaz93** [comment]
Oh cool. I'll remove it.

**Pull request merged**
