### PR TITLE
Fix regression in Popper namespace typings

### PR DESCRIPTION
**Pull request by adidahiya**
Fixes the breaking change in https://github.com/FezVrasta/popper.js/pull/539#issuecomment-372728264

### CODE REVIEW

**Comment by FezVrasta** [comment]
Isn't there any way to reduce the amount of changes?

**Comment by adidahiya** [comment]
Not really, no. I've left code comments explaining how this can be simplified if you choose to make a breaking change in 2.x

**Comment by FezVrasta** [comment]
May we do the opposite of what you are doing here?

Have all the top level exports, and at the bottom the namespace that re-exports the top-level stuff as props of the namespace?


```
export type xxx = xxx
export type yyy = yyy

export namespace Popper {
  export type xxx
  export type yyy
}
```

**Comment by adidahiya** [comment]
Unfortunately that doesn't work.

```ts
export namespace Popper {
  export type Position; // this isn't valid syntax. you need an assignment. '=' expected by tsc

  export type Position = Position; // this doesn't work because Position becomes a circular reference.
}
```

**Comment by FezVrasta** [comment]
Ok thanks. We should have some kind of types tests, may you update them to add a regression test for this thing?

**Comment by adidahiya** [comment]
Yep, I've updated the tests to verify that the regression is fixed.

**Comment by FezVrasta** [comment]
Ok thanks, waiting for feedbacks from @cwmoo740 before I merge this

**Comment by cwmoo740** [comment]
Sure, it keeps all the top level exports. I'll revisit this and update it again when it's ready for a 2.0 release. I also put a PR into 

https://github.com/palantir/blueprint/pull/2227

to reference the types this way.

Versioning types on a non-typescript project is still not a solved issue, and especially when supporting newer features in ts, type definition files shouldn't necessarily be held back by downstream users. This is one of the reasons TSC has the paths mapping feature, to allow you to hold onto old type definition files in existing projects.

Personally, if it's not causing too many issues for users, I would prefer that you merge my pr into blueprint instead, but if that's not possible, this is fine.

**Comment by FezVrasta** [comment]
Released as https://github.com/FezVrasta/popper.js/releases/tag/v1.14.1

**Pull request merged**
