### PR TITLE
[fix] Fix rounding of arrow offset

### PR DESCRIPTION
**Pull request by FezVrasta**
should fix #227

ping @atomiks

### CODE REVIEW

**Comment by atomiks** [comment]
Should be `floor()` not `round()`?

**Comment by FezVrasta** [comment]
What if is `x.9`? Isn't it better to round?

**Comment by atomiks** [comment]
The problem is that x.5 rounds up to (x+1).0 which is more incorrectly placed than x.0. Also, it is never anything other than x.0 and x.5 if it's divided by 2? I just resized the window so the arrow moved away from the center and it was always .0 or .5.

**Comment by atomiks** [comment]
So going with `floor()`? `round()` wouldn't fix the issue if it's a half pixel and rounds up rather than down (as I mentioned in the issue)

**Pull request merged**
