### PR TITLE
React.js support and improvements

### PR DESCRIPTION
**Pull request by FezVrasta**
- moved the DOM manipulating logic inside the `applyStyle` modifier
- the callback is now called using `.onCreate` method
- added `.onUpdate` callback
- improved README examples

ping @schickling @eek and @mgcrea for feedbacks

### CODE REVIEW

**Comment by schickling** [comment]
That was quite fast @FezVrasta! :+1: 

I think it would be very helpful if you'd feature a complete React component in the Readme as an example, so that there is no guess work needed.

**Comment by FezVrasta** [comment]
I've not a lof of experience with React, can someone prepare one?

**Comment by vampolo** [comment]
Separating the logic from the actual rendering is a first step into making this project more modular but i wouldn't call it React support.
What we mean *React support* might have different opinions, one that seems pretty straightforward and simpler to the user of this library would be to have a React Component that  can be used as

```
class MyElementWithPopper extends React.Component {
  render() {
    return <div>
              <div ref="reference">My text</div>
              <div ref="popper"> Content of the popper</div>
              </div>;
  }
}
```

There might be vary variations, like creating

```
<Popper reference=MyReferenceComponent popper=MyPopperComponent data=data>
```

That of course depends from how far the integration wants to go... What some libraries do like `redux` they have a base `redux` module and a `react-redux` integration...

**Comment by FezVrasta** [comment]
I think I'm then going to merge this PR as is and then I'll try to prepare something more specific to support React out of the box.

**Comment by shockwork** [comment]
@FezVrasta hey buddy, long time no see! I suggest forking it into a react-popper module, want me to do that?

**Comment by FezVrasta** [comment]
Hey @shockwork :)
Happy to see you here!

I'd like to provide a basic usage example directly in this repository to keep the informations all in the same place (I'd like to avoid people to get confused or wander around different repositories).

I think that putting the stuff inside a `react/` folder could be a good start for now. I don't expect it to need webpack and the full react-style environment.

If you have time and it's not a problem for you then I'd love to get a contribution by you.

What do you think?

**Comment by FezVrasta** [comment]
Please continue here: #6

**Pull request merged**
