### PR TITLE
fixed #144

### LINKED ISSUE #144: Error when requiring with Webpack
Hello,

### Steps to reproduce the problem

I installed both Popper.js and Tooltip.js, here is an extract from my package.json

```
"dependencies": {
    // ...
    "popper.js": "^1.0.2",
    "tooltip.js": "^1.0.2",
    // ...
}
```

I require Tooltip.js like this in my JS file:

```
const Tooltip = require('tooltip.js');
```

(same problem if I also instanciate Popper.js before)

### What is the expected behavior?

I should receive no error and be able to use Tooltip.

### What went wrong?

When I start webpack, I get the following error in my console:

```
15:27:33 client.1 | Version: webpack 1.14.0
15:27:33 client.1 | Time: 14249ms
15:27:33 client.1 |              Asset     Size  Chunks             Chunk Names
15:27:33 client.1 |  webpack-bundle.js  3.55 MB       0  [emitted]  main
15:27:33 client.1 | webpack-styles.css  0 bytes       0  [emitted]  main
15:27:33 client.1 |    [0] multi main 76 bytes {0} [built]
15:27:33 client.1 |     + 328 hidden modules
15:27:33 client.1 |
15:27:33 client.1 | ERROR in ./~/tooltip.js/dist/tooltip.es5.js
15:27:33 client.1 | Module not found: Error: Cannot resolve 'file' or 'directory' ../popper/index.js in /vagrant/client/node_modules/tooltip.js/dist
15:27:33 client.1 |  @ ./~/tooltip.js/dist/tooltip.es5.js 26:90-119
```

Thanks in advance!

### PR DESCRIPTION
**Pull request by FezVrasta**
fixed #144, please @Spone take a look at this branch and let me know if it fixed the problem for you.

### CODE REVIEW

**Comment by Spone** [comment]
Still the same error when I use the branch `fix-144`

```
"dependencies": {
    // ...
    "popper.js": "^1.0.2",
    "tooltip.js": "https://github.com/FezVrasta/popper.js.git#fix-144",
    // ...
}
```

```
13:43:50 client.1 | ERROR in ./~/tooltip.js/dist/tooltip.es5.js
13:43:50 client.1 | Module not found: Error: Cannot resolve 'file' or 'directory' ../popper/index.js in /vagrant/client/node_modules/tooltip.js/dist
13:43:50 client.1 |  @ ./~/tooltip.js/dist/tooltip.es5.js 26:90-119
```

**Comment by FezVrasta** [comment]
May you try to use the same branch also for `popper.js`?

**Comment by Spone** [comment]
Same with:

```
"dependencies": {
    // ...
    "popper.js": "https://github.com/FezVrasta/popper.js.git#fix-144",
    "tooltip.js": "https://github.com/FezVrasta/popper.js.git#fix-144",
    // ...
}
```

**Comment by FezVrasta** [comment]
Could you provide a repo where I can reproduce the problem?

**Comment by FezVrasta** [comment]
@Spone you can use 1.0.4 now that ships the compiled code with the fix

**Comment by Spone** [comment]
Hi @FezVrasta 

Thanks for your help.

I now use:

```
"dependencies": {
    // ...
    "popper.js": "^1.0.4",
    "tooltip.js": "^1.0.3",
    // ...
}
```

I still have the issue:

```
11:31:08 client.1 | Version: webpack 1.14.0
11:31:08 client.1 | Time: 12245ms
11:31:08 client.1 |              Asset     Size  Chunks             Chunk Names
11:31:08 client.1 |  webpack-bundle.js  3.55 MB       0  [emitted]  main
11:31:08 client.1 | webpack-styles.css  0 bytes       0  [emitted]  main
11:31:08 client.1 |    [0] multi main 76 bytes {0} [built]
11:31:08 client.1 |     + 328 hidden modules
11:31:08 client.1 |
11:31:08 client.1 | ERROR in ./~/tooltip.js/dist/tooltip.es5.js
11:31:08 client.1 | Module not found: Error: Cannot resolve 'file' or 'directory' ../popper/index.js in /vagrant/client/node_modules/tooltip.js/dist
11:31:08 client.1 |  @ ./~/tooltip.js/dist/tooltip.es5.js 26:90-119
```

**Comment by FezVrasta** [comment]
May you try to remove this part from the `.babelrc` shipped with `Popper.js`?

https://github.com/FezVrasta/popper.js/blob/master/.babelrc#L5-L7

**Comment by Spone** [comment]
Just tried it, same error.

**Pull request merged**
