### PR TITLE
Fixed d.ts to make positionFixed optional

### PR DESCRIPTION
**Pull request by k2snowman69**
The new prop `positionFixed` is optional based on my reading of the code. If you currently depend on 1.13.0 (e.g. popper.js@next) you get a build failure requiring this property to be defined. Simple fix is to make it optional.

### CODE REVIEW

**Comment by k2snowman69** [comment]
Resolves https://github.com/FezVrasta/popper.js/issues/534
Possible conflicts with https://github.com/FezVrasta/popper.js/pull/539

**Comment by k2snowman69** [comment]
@FezVrasta Any complaints?

**Comment by MrFrankel** [comment]
👍 on this as it seems to be my fault..

**Comment by FezVrasta** [comment]
There are some conflicts, once resolved we can merge it. Sorry for the delay

**Comment by k2snowman69** [comment]
Conflicts resolved! Also, what's the timeline on the positionFixed going into production? It's an awesome feature and it solves soo many problems for my layouts!

**Comment by MrFrankel** [comment]
@k2snowman69 I think this can be closed now with v1.14.1 out

**Comment by MrFrankel** [comment]
@k2snowman69 I think this can be closed no with v1.14.1

**Pull request merged**
