### PR TITLE
jsdoc param name fix (typo)

### PR DESCRIPTION
**Pull request by 719media**
minor typo

### CODE REVIEW

**Comment by FezVrasta** [comment]
This file is generated by grunt from the master branch. You should edit the source code.

**Comment by FezVrasta** [comment]
I've fixed it properly with 910b70705ce6e25b39e8ebf726aae4344cf82d8a

**Comment by 719media** [comment]
Thanks

I guess I don't follow, it looks to me that we edited the same files in the same branch. (doc/documentation.md and src/popper.js)

**Comment by FezVrasta** [comment]
Sorry you are right, I thought you was pusing to `gh-pages` 😓 sorry

**Pull request closed without merging**
