### PR TITLE
Fix #328 Tooltip offset

### LINKED ISSUE #328: Tooltip.js: offset is never set (either with "offset" or "modifiers")
- Tooltip.js v1.1.4
- Popper.js v1.10.6

### CodePen demo

https://codepen.io/hekigan/pen/GEyazB/?editors=1011

### Steps to reproduce the problem

On the codepen above, you can see that the **offset** is never set.

```
{
    ...
    offset: 100,
    popperOptions: {
      modifiers: {
        offset: {
          offset: 200
        }
      }
    }
```

### What is the expected behavior?

The tooltip should have shifted from the target element by 'x' pixels.

### What went wrong?

No change whatsoever.

### Any other comments?

I looked up in the 'tooltip.js' source code and I could not find where you set the offset and pass it on to 'popper.js'.
I did see that you merge the options object, but after that, it just does not seem to get used.

### PR DESCRIPTION
**Pull request by Akryum**

### CODE REVIEW

**Comment by FezVrasta** [comment]
Hi, sorry for the unresponsiveness!

May you add a test to make sure we don't regress here and the PR does actually fix the problem?

**Comment by FezVrasta** [comment]
Are you still interested in this PR @Akryum?

**Comment by Akryum** [comment]
I didn't have time to write tests yet.

**Comment by FezVrasta** [comment]
Ok no problem! Let me know if you need any help

**Pull request closed without merging**
