### PR TITLE
fix: lazily check for IE10

### LINKED ISSUE #238: 1.8.4: Regression: ReferenceError: navigator is not defined
In 1.8.4 the IE10 detection was changed from lazy (within the `getBoundingClientRect` method) to eager (in the global scope):

https://github.com/FezVrasta/popper.js/commit/d185897814c2b44e55a53d59d5cd9653018fe4fe#diff-948f8780a0b0051f85e85abd0b5337c4R7

The problem with that is, that parts of our app runs in a node context - and due to popper doing the check eagerly (see https://github.com/FezVrasta/popper.js/commit/d185897814c2b44e55a53d59d5cd9653018fe4fe#diff-948f8780a0b0051f85e85abd0b5337c4R7) this now fails in the node context with:

```
/var/lib/buildkite-agent/builds/canva-org/canva-web-build/web/target/build/stories/stories.js:31292
  return navigator.appVersion.indexOf('MSIE 10') !== -1;
         ^
 
ReferenceError: navigator is not defined
    at runIsIE10 (/var/lib/buildkite-agent/builds/canva-org/canva-web-build/web/target/build/stories/stories.js:31292:10)
    at Object../node_modules/popper.js/dist/esm/popper.js (/var/lib/buildkite-agent/builds/canva-org/canva-web-build/web/target/build/stories/stories.js:31295:16)
    at __webpack_require__ (/var/lib/buildkite-agent/builds/canva-org/canva-web-build/web/target/build/stories/stories.js:20:30)
    at Object../src/ui/pin/pin.tsx (/var/lib/buildkite-agent/builds/canva-org/canva-web-build/web/target/build/stories/stories.js:68362:14)
    at __webpack_require__ (/var/lib/buildkite-agent/builds/canva-org/canva-web-build/web/target/build/stories/stories.js:20:30)
    at Object../src/ui/flyout/flyout.tsx (/var/lib/buildkite-agent/builds/canva-org/canva-web-build/web/target/build/stories/stories.js:65476:13)
    at __webpack_require__ (/var/lib/buildkite-agent/builds/canva-org/canva-web-build/web/target/build/stories/stories.js:20:30)
    at Object.<anonymous> (/var/lib/buildkite-agent/builds/canva-org/canva-web-build/web/target/build/stories/stories.js:65533:16)
    at Object../src/ui/flyout/stories/flyout.stories.tsx (/var/lib/buildkite-agent/builds/canva-org/canva-web-build/web/target/build/stories/stories.js:65546:30)
    at __webpack_require__ (/var/lib/buildkite-agent/builds/canva-org/canva-web-build/web/target/build/stories/stories.js:20:30)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

can we move the IE10 detection back into the method where it is actually used, so it will only be executed if a `Popper` instance is actually constructed? Opened #240.

### PR DESCRIPTION
**Pull request by joscha**
fixes #238

### CODE REVIEW

**Comment by FezVrasta** [comment]
I moved these check outside the functions to avoid to call them on each call (if we are on IE, we are on IE, it will never change).

Could you change the checks to not fail on Node.js instead?

**Comment by joscha** [comment]
> Could you change the checks to not fail on Node.js instead?

Generally I think avoiding side-effects by imports should be the way to go, but sure, I can guard that call.

**Comment by FezVrasta** [comment]
I understand but at the moment I prefer to improve performance rather than have a super clear code for Node.js.

**Comment by joscha** [comment]
> I understand but at the moment I prefer to improve performance rather than have a super clear code for Node.js.

sure, change is in f2cea9d

**Comment by FezVrasta** [comment]
Would you like to add a test for Node in a separated PR maybe?

**Comment by joscha** [comment]
> Would you like to add a test for Node in a separated PR maybe?

can do, which test runner would you like me to use? mocha? Because currently everything seems to be run in karma, which has all those globals.

**Comment by FezVrasta** [comment]
Maybe Jest? So we move all our unit tests there add well.

**Comment by joscha** [comment]
Jest has JSDOM by default, which fills all the attributes that break in a pure node env I think?

**Comment by FezVrasta** [comment]
Nope yup have to enable it manually

**Comment by joscha** [comment]
> Nope yup have to enable it manually

👍 jest it is then :) Do you want this as a prereq for this PR being merged or can we do that independently?

**Comment by FezVrasta** [comment]
It's okay in a new pr

**Comment by FezVrasta** [comment]
I was thinking that alternatively we could cache the value the first time the function is ran and reuse it at subsequent calls. This would probably be clear? What do you think?

**Comment by joscha** [comment]
thanks @FezVrasta - can we get this and #238 in a patch release?

**Comment by FezVrasta** [comment]
1.8.5

**Pull request merged**
