### PR TITLE
Make isIE minifier-friendly

### PR DESCRIPTION
**Pull request by atomiks**
Noticed a semi-substantial increase in file size due to the new util...

A closure can be also used instead of the external "cache" object

Old: 472 bytes
New: 132 bytes

### CODE REVIEW

**Comment by FezVrasta** [comment]
Thanks!

**Comment by atomiks** [comment]
Managed to get it down to 132 bytes. I noticed the tests didn't fail (running `yarn test`) due to that though?

**Comment by FezVrasta** [comment]
Tests for IE are often disabled because the browser is too unstable to reliably run tests..

**Comment by atomiks** [comment]
You could do a mock with a UA string of IE11 and IE10

**Comment by FezVrasta** [comment]
Feel free to add a test for it if you have time

**Comment by atomiks** [comment]
@FezVrasta does this fail in Node environments without `navigator` global (since it's executed immediately)? Is there any test for that? I think the `isBrowser` var needs to be imported here...

**Comment by atomiks** [comment]
@FezVrasta did you see the above comment?

**Comment by FezVrasta** [comment]
I don't think there are tests for it. Send a PR if you notice any problem please.

**Pull request merged**
