### PR TITLE
types: tooltip.js typing and remove namespaces/declare module from po…

### PR DESCRIPTION
**Pull request by cwmoo740**
It's no longer best practice to use "declare module" and "declare namespace" in .d.ts files - they can export all of their types at the top level.

Closes issue https://github.com/FezVrasta/popper.js/issues/372

### CODE REVIEW

**Comment by FezVrasta** [comment]
Thanks, we had a lot of problems with TypeScript definitions, I'd really like to have some kind of CI test to make sure them work, any idea?

**Comment by cwmoo740** [comment]
I can add some typescript sample files and integrate them into your build plan - it will check that code samples of using your component API compile correctly.

Should I do that in this pull request?

**Comment by FezVrasta** [comment]
Yes please! 🤗

**Comment by cwmoo740** [comment]
There are a few new files:

`packages/(popper|tooltip)/tests/types/typing-test.ts` have ts code that creates some objects and calls the public api to make sure it compiles. These are run as new posttest scripts for each of those two packages.

**Comment by cwmoo740** [comment]
I'm not sure the CI issues are related to my changes. I can back out any non-typescript changes to the yarn.lock if necessary.

**Comment by cwmoo740** [comment]
@FezVrasta is this pr ready to merge?

**Comment by FezVrasta** [comment]
I think so, I'm going to hold on on it until I get back home next week tho, I don't have enough time to dedicate to this atm

**Comment by cwmoo740** [comment]
@FezVrasta any updates?

**Comment by FezVrasta** [comment]
It looks good to me, I guess I'm going to merge this hoping nobody will open issues later... eheh

**Comment by cwmoo740** [comment]
Ping me and I'll help you deal with them too

**Comment by adidahiya** [comment]
This is a breaking change in the typings, and it should be reverted. Previously, the _default export_ was a namespace which included types as members. Now, all the types are exported from the top-level of the module _next to_ the default export. Although this is better aesthetically and probably the right direction, it is a breaking change and cannot be done in the 1.x range of this library. It caused this issue downstream: https://github.com/palantir/blueprint/issues/2226

**Comment by FezVrasta** [comment]
@cwmoo740 is there any way to export the namespace and keep the other changes?

**Comment by adidahiya** [comment]
Yes, I think that should be possible. I'll try to put together a quick PR.

**Comment by cwmoo740** [comment]
@adidahiya there's still no convention of following semver for typing - DefinitelyTyped clearly doesn't follow semver when making breaking changes by upgrading tsc versions, for example. Exporting an additional namespace that rolls up the types again is fine, but don't revert the typings to older syntax discouraged by typescript when you should probably upgrade your library instead.

**Comment by adidahiya** [comment]
This isn't DefinitelyTyped. This is an NPM-published library that is depended on by other TypeScript libraries. Downstream consumers shouldn't be able to pick up a minor release and have it break their build -- it's as simple as that.

**Comment by adidahiya** [comment]
I opened #584 to address this.

**Pull request merged**
