### PR TITLE
AngularJS led me to a wrapper for Angular +2

### PR DESCRIPTION
**Pull request by kimdah3**
This led me to a wrapper for Angular +2

### [angular-popper](https://www.npmjs.com/package/angular-popper)

This component is in alpha base, you can contribute to it!

### CODE REVIEW

**Comment by FezVrasta** [comment]
I'm not familiar with the Angular nomenclature, may you simply fix the name instead of delete the whole entry?

**Comment by Johann-S** [comment]
yep that's not `AngularJS` which is related to `AngularJS` v1.x it's `Angular` which is related to `Angular` v2+

**Comment by kimdah3** [comment]
It could be moved to Angular and then remove the AngularJS title because I can't find a wrapper.

**Comment by MrFrankel** [comment]
@kimdah3 if you are looking for an Angular wrapper I can also suggest mine.
[https://github.com/MrFrankel/ngx-popper](https://github.com/MrFrankel/ngx-popper)

**Comment by MrFrankel** [comment]
@FezVrasta Mine is already mentioned 👍

**Pull request closed without merging**
