### PR TITLE
Updates Dependencies

### PR DESCRIPTION
**Pull request by CDAGaming**
Please View Changes to see exact Dependencies Updated

Signed-off-by: CDAGaming <cstack2011@yahoo.com>

### CODE REVIEW

**Comment by FezVrasta** [comment]
Thank you, you should update the yarn.lock file as well

**Comment by CDAGaming** [comment]
Ok :)
Not on my PC, so I'll edit from mobile so hopefully the builds still succeed

**Comment by CDAGaming** [comment]
Oddly enough, all builds have been failing after https://github.com/FezVrasta/popper.js/commit/37925b5d483bf92618b909d5838eb14edeb8293d

**Comment by CDAGaming** [comment]
@FezVrasta Yarn.lock Updated via AutoGeneration vis yarn Upgrade 👍

**Comment by CDAGaming** [comment]
Merging with master, in theory should fix final build checks

**Comment by CDAGaming** [comment]
@FezVrasta There is a verify and build error you may wanna look into:
`[flipping] flips to bottom when hits top viewport edge FAILED`

**Comment by CDAGaming** [comment]
Yup, just that error is why Travis Failed, hope your able to make a fix for it

**Comment by FezVrasta** [comment]
I'll look at this when I have some time, thank you

**Comment by CDAGaming** [comment]
Happy To Assist. Let me know if bug is fixed soon, so i can do a rebuild commit so travis succeeds

**Pull request merged**
