### PR TITLE
Use the arrow element's parent to compute margin and border

### LINKED ISSUE #710: Arrow position incorrect when an inner element has a border
### CodePen demo

https://codepen.io/anon/pen/dQpGdm

### Steps to reproduce the problem

I noticed this after creating a tooltip theme with a border.

img

1.  Zoom right into both demos

- The top one has an inner element with the arrow inside it, and its position is incorrect (1px too far -- happens for both horiz and vertical placements).

- The bottom one has the arrow directly inside the popper, and its position is correct.

It only happens when the inner element has a `border`.

### What is the expected behavior?

Correct position of the arrow

### What went wrong?

Arrow is 1px too far (aka the `top` for horizontal placement and `left` for vertical placement is rounded? too much).

### PR DESCRIPTION
**Pull request by atomiks**
Fixes #710 

Can't seem to run the tests.

New: https://codepen.io/anon/pen/yQXRaG (line 1412)
Old: https://codepen.io/anon/pen/dQpGdm (v1.14.5)

I'm kind of worried about this assumption as a change to the behavior but it seems necessary to fix the problem mentioned in the issue

### CODE REVIEW

**Comment by FezVrasta** [comment]
Doesn't this break the other case? (when the popper has a margin)?

**Comment by atomiks** [comment]
In the CodePen, it looks like the arrow is correctly placed when the popper has a border as well still. 

As for margin, well if you add `margin-bottom: 1px` to the `#tip, #pop2` selector, it's incorrectly placed for both `data.instance.popper` and `arrowElement.parentNode`. Not sure if it's expected.

**Comment by atomiks** [comment]
If the arrow was not a direct child of the popper, and the popper has a border/margin, then it changes the behavior. 

No change here:

```html
<div id="pop" style="border: 1px solid black;">
  <div x-arrow></div>
</div>
```

Behavior changes here:

```html
<div id="pop" style="border: 1px solid black;">
  <div>
    <div x-arrow></div>
  </div>
</div>
```

However I don't think this would ever be the case because you need a positioning context  to position the arrow properly which would mean the direct parent would have the styling. 

Generally, most would do this:

```html
<div id="pop">
  <div style="border: 1px solid black;">
    <div x-arrow></div>
  </div>
</div>
```

Maybe to prevent breaking current behavior we need to also check the popper too

**Comment by atomiks** [comment]
@FezVrasta I've made some changes so it's backwards-compatible now

Could you run the tests on it? 🙏

**Comment by FezVrasta** [comment]
@atomiks tests run automatically on Travis CI. They are passing, but I don't think we have an extensive test suite for the arrow modifier in any case.

I will test this manually when I find some time. Thanks!

**Comment by atomiks** [comment]
It would be cool to get this and the rounding fix in a new patch release 💙

**Comment by atomiks** [comment]
Gonna close due to bloat caused by backwards compatibility. Maybe consider it for v2. For now you can use a `translate` rule to correct it by 1px for bordered themes...

**Pull request closed without merging**
